### ISSUE TITLE
Upgrade to latest Undertow

### ISSUE THREAD

**Issue by stephlag** [kohesive/solr-undertow#31]
Latest version is 1.3.23.Final

**Comment by apatrida** [comment]
I'll upgrade when there is a retest opportunity, otherwise it is dangerous when it cannot be run through the paces or a known problem.

**Comment by stephlag** [comment]
I will test it on a branch as I am interested on running Solr with Undertow.

**Comment by apatrida** [comment]
I don't see anything in release notes that would be useful at this point to upgrade.  1.4.0-Final is due soon, so that would be better to wait and test with it.  

There are no perfromance gains in 1.3.23 over 1.3.18 and no bugs I can see that would affect Solr-Undertow.

1.4.0 upgrade will happen after it is released and tested again.  will update Solr in examples and dependencies across the board.

**Comment by stephlag** [comment]
ok
